### PR TITLE
Fix: correct using start and end arguments for newGetNewsCommand

### PR DESCRIPTION
**Pull request by sklymoshenko**
Using a start argument of a function as start argument for xtb API

### CODE REVIEW

**Comment by kejrak** [comment]
Thank you for the catch @sklymoshenko. Merging right away!

**Comment by kejrak** [comment]
@sklymoshenko Can you please change the commit message to conventional commit message? (https://www.conventionalcommits.org/en/v1.0.0/)?

**Comment by sklymoshenko** [comment]
@kejrak you want me to add prefix `fix:` at the beginning or something else too?

**Comment by kejrak** [comment]
Fix will do just fine, thank you. @sklymoshenko

**Pull request merged**
